#pragma once
#include <iostream>
#include <string>
#include <queue>
#include <memory>
#include <fstream>
#include <GLEW\glew.h>
#include <GLFW\glfw3.h>
#include <sstream>
#include <algorithm>
#include <functional>
using std::cout;
using std::endl;
using std::string;
using std::queue;